use ECM;

DROP TABLE STAGE;
DROP TABLE TUTEUR;
DROP TABLE ENTREPRISE;
DROP TABLE COMPETENCE;
DROP TABLE ETUDIANT;
DROP TABLE PROMO;
DROP TABLE TYPE_STAGE;
DROP TABLE PROFESSEUR;
DROP TABLE ADRESSE;

--SUPPRESSION DES TABLES
